sudo: false
language: go
go:
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 1.9.4
  - 1.9.5
  - 1.10.1
  - 1.10.2
before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=rrule.coverprofile
  - goveralls -coverprofile=rrule.coverprofile -service=travis-ci
